name: Gradle Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 0 # Fetch all history for all tags and branches

    - name: Verify Submodule Checkout and Configuration
      run: |
        echo "--- Verifying .gitmodules content ---"
        cat .gitmodules || echo ".gitmodules not found or unreadable"
        echo ""
        echo "--- Verifying .git/config content after checkout ---"
        cat .git/config || echo ".git/config not found or unreadable"
        echo ""
        echo "--- Final git submodule status (--recursive) ---"
        git submodule status --recursive || echo "Failed to get submodule status"
        echo ""
        echo "--- Listing opensdk directory ---"
        ls -la opensdk || echo "opensdk directory not found"
        echo ""
        echo "--- Attempting to display opensdk/build.gradle ---"
        cat opensdk/build.gradle || echo "opensdk/build.gradle not found"

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3.3.1
      with:
        gradle-version: '8.7'

    - name: Generate Gradle Wrapper files
      run: gradle wrapper
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Package
        path: build/libs 