name: Gradle Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main repository
      uses: actions/checkout@v4
      #  submodules: 'recursive' # Убрали пока, чтобы проверить шаги ниже
      #  persist-credentials: false # Можно раскомментировать для теста

    - name: Debug and Initialize Submodules
      run: |
        echo "--- Current directory structure (before submodule operations) ---"
        ls -la
        echo ""
        echo "--- Verifying .gitmodules content ---"
        cat .gitmodules || echo ".gitmodules not found or unreadable"
        echo ""
        echo "--- Forcing submodule synchronization (git submodule sync --recursive) ---"
        git submodule sync --recursive
        echo ""
        echo "--- Forcing submodule initialization (git submodule update --init --recursive --force) ---"
        git submodule update --init --recursive --force
        echo ""
        echo "--- Final git submodule status ---"
        git submodule status || echo "Failed to get submodule status after all attempts"
        echo ""
        echo "--- Listing opensdk directory (after all attempts) ---"
        ls -la opensdk || echo "opensdk directory STILL not found"
        echo ""
        echo "--- Attempting to display opensdk/build.gradle (after all attempts) ---"
        cat opensdk/build.gradle || echo "opensdk/build.gradle STILL not found"

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3.3.1
      with:
        gradle-version: '8.7'

    - name: Generate Gradle Wrapper files
      run: gradle wrapper
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Package
        path: build/libs 